#!/bin/bash
# =============================================================================
# Generate Realistic Images for FINAL QA Specialist Pool
# =============================================================================
#
# This script generates REALISTIC images for the specialist 330 pool cards
# as defined in Assignments.csv.
#
# Supports two modes:
# - Synchronous (default): Real-time generation using S4 image generator
# - Batch (--batch): Async generation using Batch API (faster for large batches)
#
# Prerequisites:
# - Assignments.csv must exist (generated by generate_final_qa_assignments.py)
# - S3 image spec must exist (s3_image_spec__armG.jsonl)
# - S4 image generator is available
#
# Usage:
#   ./run_s4_realistic_images.sh [options]
#
# Options:
#   --workers N      Number of parallel workers (default: 3)
#   --dry-run        Show what would be generated without generating
#   --resume         Resume from previous run (retry failed images)
#   --overwrite      Overwrite existing images
#   --batch          Use batch API for async generation
#   --check-status   Check batch job status
#
# Reference:
# - Phase 5-3 in s5-finaldistribution-armg-integrated plan
# - AppSheet_Realistic_Image_Evaluation_Design.md
# =============================================================================

set -euo pipefail

# Configuration
RUN_TAG="${RUN_TAG:-FINAL_DISTRIBUTION}"
ARM="${ARM:-G}"
BASE_DIR="${BASE_DIR:-.}"
WORKERS="${WORKERS:-3}"

# Parse command line arguments
DRY_RUN=""
RESUME=""
OVERWRITE=""
BATCH=""
CHECK_STATUS=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --workers)
            WORKERS="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN="--dry_run"
            shift
            ;;
        --resume)
            RESUME="--resume"
            shift
            ;;
        --overwrite)
            OVERWRITE="--overwrite"
            shift
            ;;
        --batch)
            BATCH="--batch"
            shift
            ;;
        --check-status)
            CHECK_STATUS="--check_status"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Paths
ASSIGNMENTS_PATH="${BASE_DIR}/2_Data/metadata/generated/${RUN_TAG}/appsheet_export/Assignments.csv"
SCRIPT_PATH="${BASE_DIR}/3_Code/src/tools/s4/generate_realistic_images.py"

echo "============================================="
echo " S4 Realistic Image Generation"
echo "============================================="
echo "RUN_TAG:     ${RUN_TAG}"
echo "ARM:         ${ARM}"
echo "WORKERS:     ${WORKERS}"
echo "BASE_DIR:    ${BASE_DIR}"
echo "ASSIGNMENTS: ${ASSIGNMENTS_PATH}"
if [[ -n "${BATCH}" ]]; then
    echo "MODE:        BATCH (async)"
elif [[ -n "${CHECK_STATUS}" ]]; then
    echo "MODE:        CHECK STATUS"
else
    echo "MODE:        SYNC (real-time)"
fi
echo ""

# Check prerequisites (skip for --check-status mode)
if [[ -n "${CHECK_STATUS}" ]]; then
    echo "[INFO] Checking batch status..."
    echo "---------------------------------------------"
    
    python3 "${SCRIPT_PATH}" \
        --base_dir "${BASE_DIR}" \
        --run_tag "${RUN_TAG}" \
        --arm "${ARM}" \
        --check_status
    
    EXIT_CODE=$?
    echo "---------------------------------------------"
    exit ${EXIT_CODE}
fi

if [[ ! -f "${ASSIGNMENTS_PATH}" ]]; then
    echo "[ERROR] Assignments.csv not found at: ${ASSIGNMENTS_PATH}"
    echo ""
    echo "Please run generate_final_qa_assignments.py first to create Assignments.csv"
    exit 1
fi

S3_SPEC_PATH="${BASE_DIR}/2_Data/metadata/generated/${RUN_TAG}/s3_image_spec__arm${ARM}.jsonl"
if [[ ! -f "${S3_SPEC_PATH}" ]]; then
    echo "[ERROR] S3 image spec not found at: ${S3_SPEC_PATH}"
    exit 1
fi

echo "[INFO] Assignments file found"
echo "[INFO] S3 spec file found"
echo ""

# Count specialist assignments
SPECIALIST_COUNT=$(grep -c "specialist" "${ASSIGNMENTS_PATH}" 2>/dev/null || echo "0")
echo "[INFO] Specialist assignments: ${SPECIALIST_COUNT}"

# Run the generator
echo ""
echo "[INFO] Starting realistic image generation..."
echo "---------------------------------------------"

python3 "${SCRIPT_PATH}" \
    --base_dir "${BASE_DIR}" \
    --run_tag "${RUN_TAG}" \
    --arm "${ARM}" \
    --assignments "${ASSIGNMENTS_PATH}" \
    --workers "${WORKERS}" \
    ${DRY_RUN} \
    ${RESUME} \
    ${OVERWRITE} \
    ${BATCH}

EXIT_CODE=$?

echo ""
echo "---------------------------------------------"
if [[ ${EXIT_CODE} -eq 0 ]]; then
    echo "[SUCCESS] Realistic image generation completed"
    
    # Show output directory
    IMAGES_DIR="${BASE_DIR}/2_Data/metadata/generated/${RUN_TAG}/images_realistic"
    if [[ -d "${IMAGES_DIR}" ]]; then
        IMAGE_COUNT=$(find "${IMAGES_DIR}" -name "*.jpg" | wc -l)
        echo "[INFO] Generated images: ${IMAGE_COUNT}"
        echo "[INFO] Output directory: ${IMAGES_DIR}"
    fi
else
    echo "[ERROR] Realistic image generation failed with exit code ${EXIT_CODE}"
fi

echo "============================================="
exit ${EXIT_CODE}

